# Лабораторная работа №0 (Numpy)

Выполнил: Гершевский Егор, гр. 6131-010402D

0 Импортируем библиотеку для выполнения лабораторной работы.

In [1]:
import numpy as np

np.__version__

'1.19.5'

1 Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать их работу. Для каждой функции добавить комментарий.

In [9]:
#1.1 Creating array
a = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [8]:
#1.2 Creating random array
b = np.random.random((3,3))
b

array([[0.05947856, 0.31434455, 0.48238684],
       [0.93223594, 0.25429215, 0.44847538],
       [0.25316367, 0.64335795, 0.79879268]])

In [10]:
#1.3 Array-wise sum
b.sum()

4.186527732706276

In [13]:
#1.4 Array-wise minimum value
b.min()

0.05947856317173528

In [18]:
#1.5 Maximum value of an array rows
b.max(axis=0)

array([0.93223594, 0.64335795, 0.79879268])

In [17]:
#1.6 Mean
b.mean()

0.4651697480784751

In [19]:
#1.7 Flatten the array
b.ravel()

array([0.05947856, 0.31434455, 0.48238684, 0.93223594, 0.25429215,
       0.44847538, 0.25316367, 0.64335795, 0.79879268])

In [20]:
#1.8 Return sorted unique values
np.unique(b)

array([0.05947856, 0.25316367, 0.25429215, 0.31434455, 0.44847538,
       0.48238684, 0.64335795, 0.79879268, 0.93223594])

In [21]:
#1.9 Convert 'b' to a Python list
b.tolist()

[[0.05947856317173528, 0.3143445464310548, 0.4823868426911694],
 [0.9322359414008041, 0.25429215260984384, 0.4484753816688779],
 [0.2531636738521522, 0.6433579503918917, 0.7987926804887464]]

In [22]:
#1.10 View documentation for 'np.eye'
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [23]:
#1.11 Appends values to the end of 'a'
np.append(a, 10.0)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
#1.12 Deletes rows on index 2 of 'a'
np.delete(a, 2, axis=0)

array([[1., 2., 3.],
       [4., 5., 6.]])

2 Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам. <br/>
Оси: <br/>
    0: ID группы товаров <br/>
    1: ID магазина <br/>
    2: День месяца, в котором осуществляются продажи (предположим у нас в OLAP-кубе собраны продажи за месяц). <br/>

Содержимое ячейки: продажи в тыс. рублей данной категории товаров в данном магазине в данный день. <br/>

Рекомендуется сгенерировать статистически-правдопододные данные в ячейках.
К примеру, будет странно, если продажи одной и той же группы товаров в соседние дни будут представлять из себя "белый шум". Пусть будет какой-то правдоподобное распределение на ваш вкус.
Также продажи одних и тех же групп товаров в разных магазинах не могут отличаться в сотни и тысячи раз, максимум в разы.
Подумайте как это обыграть используя различные функции генерации случайных чисел + "смекалку".

In [31]:
id_item = np.arange(0, 100, 1)
id_magazine = np.arange(0, 10, 1)
date = np.arange(1, 28, 1) #Let it be February

olap_cube = np.zeros([id_item.size, id_magazine.size, date.size])

for item in range(id_item.size):
    for magazine in range(id_magazine.size):
        for days in range(date.size):
            olap_cube[item, magazine, days] = np.random.randint(1, 100)

In [32]:
olap_cube

array([[[10., 45., 68., ..., 44., 31., 45.],
        [75., 53., 66., ..., 51., 44., 94.],
        [54., 29., 78., ..., 90., 77., 13.],
        ...,
        [10., 99., 69., ...,  9., 27., 29.],
        [33., 45., 98., ..., 27., 19., 94.],
        [91., 69., 41., ..., 58., 82., 19.]],

       [[13., 99., 10., ..., 19., 33., 99.],
        [11., 79., 41., ..., 17.,  2., 13.],
        [ 2.,  3.,  6., ..., 34., 77., 31.],
        ...,
        [98., 55., 61., ..., 76., 53., 40.],
        [72., 74., 93., ..., 26., 48., 83.],
        [15., 91., 94., ..., 22., 40., 28.]],

       [[ 6., 39., 92., ..., 18., 38., 17.],
        [18., 94., 25., ..., 81., 61., 98.],
        [90., 29., 73., ..., 55., 84., 24.],
        ...,
        [58., 87., 31., ..., 10., 29., 52.],
        [ 3., 75., 33., ..., 60.,  9., 81.],
        [ 3., 10., 61., ..., 82., 38., 92.]],

       ...,

       [[46.,  3., 90., ...,  2., 55., 29.],
        [18., 97., 33., ..., 30., 79., 93.],
        [41., 74.,  1., ..., 91., 18., 54.

3 Для получившегося OLAP-куба посчитать суммарные, средние, минимальные и максимальные продажи (на самом деле любые агрегатные функции можно использовать)зафиксировав значения по одной, двум или трём осям:

Например взять какой-то определённый набор товаров и набор городов или диапазон дней и сагрегировать данные по всем ячейкам из зафиксированного набора.
Пример: получить сумму, среднее, минимум и максимум по продажам 10-20 чисел месяца для товаров [1,3,4] по всем городам (или по конкретному набору городов).

Попробуйте различные варианты индексации и различные варианты срезов, насколько хватит фантазии.

In [52]:
print('Sum of sales of all products per month:', np.sum(olap_cube[:,:,:]), 'conventional units')
print('The sum of sales of all goods of store No.7 per month:', np.sum(olap_cube[:,7,:]), 'conventional units')
print('Average monthly sales of store No.1: %.1f' %np.mean(olap_cube[:, 1, 1:28]), 'conventional units')

Sum of sales of all products per month: 1347740.0 conventional units
The sum of sales of all goods of store No.7 per month: 134350.0 conventional units
Average monthly sales of store No.1: 50.1 conventional units


![olap-cube](http://www.olap.ru/basic/img/alpero2i2.gif)